export const restaurants = [
  {
    id: 1,
    name: "Spice Villa",
    image: "https://source.unsplash.com/300x200/?indian-food",
    address: "MG Road, Pune",
    type: "South Indian",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Burger Town",
    image: "https://source.unsplash.com/300x200/?burger",
    address: "Koregaon Park, Pune",
    type: "Fast Food",
    rating: 4.2,
  },
  {
    id: 3,
    name: "Green Leaf Mess",
    image: "https://source.unsplash.com/300x200/?healthy-food",
    address: "Baner, Pune",
    type: "Mess/Tiffin Service",
    rating: 4.8,
  },
  {
    id: 4,
    name: "Dragon Bowl",
    image: "https://source.unsplash.com/300x200/?chinese-food",
    address: "Viman Nagar, Pune",
    type: "Chinese Restaurant",
    rating: 4.1,
  },
  {
    id: 5,
    name: "The Food Court",
    image: "https://source.unsplash.com/300x200/?restaurant",
    address: "Hinjewadi Phase 1, Pune",
    type: "Multi-Cuisine",
    rating: 4.0,
  },
  {
    id: 6,
    name: "Dosa Delight",
    image: "https://source.unsplash.com/300x200/?dosa",
    address: "FC Road, Pune",
    type: "South Indian",
    rating: 4.3,
  },
  {
    id: 7,
    name: "Urban Tandoor",
    image: "https://source.unsplash.com/300x200/?tandoori",
    address: "Kalyani Nagar, Pune",
    type: "North Indian",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Mom's Mess",
    image: "https://source.unsplash.com/300x200/?home-cooked-food",
    address: "Katraj, Pune",
    type: "Mess/Tiffin Service",
    rating: 4.7,
  },
  {
    id: 9,
    name: "Cafe Brew Beans",
    image: "https://source.unsplash.com/300x200/?coffee",
    address: "Deccan Gymkhana, Pune",
    type: "Cafe",
    rating: 4.4,
  },
  {
    id: 10,
    name: "Taste of Punjab",
    image: "https://source.unsplash.com/300x200/?punjabi-food",
    address: "Hadapsar, Pune",
    type: "North Indian",
    rating: 4.2,
  },
];
